image:
  pullPolicy: Always
  tag: edge-arm64

args:
  - --v=4
  # - --cluster=test
  - --prometheus-url=http://vmsingle-vm.monitoring.svc:8429

config:
  bases:
    cpu:
      series: container_cpu_usage_seconds_total
      unit: cores
      scope: pod
      aggregation: raw
    memory:
      series: container_memory_working_set_bytes
      unit: bytes
      scope: pod
      aggregation: raw
    node_cpu:
      series: node_cpu_usage_cores
      unit: cores
      scope: node
      aggregation: raw
    node_memory:
      series: node_memory_used_bytes
      unit: bytes
      scope: node
      aggregation: raw

tls:
  type: "helm"

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

priorityClassName: system-cluster-critical

podAntiAffinityPreset: hard
podAntiAffinityPresetKey: kubernetes.io/hostname

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
