---
# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 8
    rebase-strategy: disabled
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
    cooldown:
      default-days: 7
    groups:
      docker:
        patterns:
          - "docker/*"
      actions:
        patterns:
          - "actions/*"

  - package-ecosystem: "gomod"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 8
    rebase-strategy: disabled
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
    cooldown:
      default-days: 7
    groups:
      main:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/custom-metrics-apiserver"
          - "github.com/prometheus/*"
